services:
  - type: web
    name: fintech-sales-intelligence
    env: docker
    plan: starter
    region: oregon

    dockerfilePath: Dockerfile

    branch: main

    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: MYSQL_USER
        sync: false

      - key: MYSQL_PASSWORD
        sync: false

      - key: MYSQL_DB
        sync: false

      - key: MYSQL_HOST
        sync: false

      - key: MYSQL_PORT
        sync: false

      - key: REDIS_URL
        sync: false

      - key: SECRET_KEY
        sync: false

      - key: OPENAI_API_KEY
        sync: false

      - key: TAVILY_API_KEY
        sync: false

      - key: APP_ENV
        value: production

      - key: DB_INIT
        value: "true"